add systemTopic($baidu, $link) support
baetyl/baetyl-broker pull request #13
Opened 2019-12-19 09:35 UTC by kuailehaibin

add systemTopic($baidu, $link) support

2019-12-20 00:51 UTC, ludanfeng requested changes

2019-12-20 00:51 UTC, ludanfeng commented on common/topic.go
> +	// maxTopicLevels = 9
恢复

2019-12-20 00:51 UTC, ludanfeng commented on exchange.go
> +	bindings map[string]*mqtt.Trie
broker配置增加如下配置，避免hardcode:
systemTopics:
     - baidu
     - link

2019-12-20 00:51 UTC, ludanfeng commented on exchange.go
> +	}
parts := strings.SplitN(topic, "/", 2)
b, ok := b.bindings[parts[0]]
if ok {
b.Remove(parts[1], queue)
return
} 

// common
b.bindings["/"].Remove(topic, queue)
}

2019-12-20 00:54 UTC, ludanfeng requested changes

2019-12-20 00:54 UTC, ludanfeng commented on session/client_mock_test.go
> +	if strings.HasPrefix(topic, "$baidu/") {
各种if else是最糟糕的实现

2019-12-22 17:25 UTC, kuailehaibin commented on session/client_mock_test.go
> +	if strings.HasPrefix(topic, "$baidu/") {
我调整一下

2019-12-22 17:25 UTC, kuailehaibin commented on exchange.go
> +	}
OK

2019-12-22 17:26 UTC, kuailehaibin commented on common/topic.go
> +	// maxTopicLevels = 9
好

2019-12-22 17:30 UTC, kuailehaibin commented on exchange.go
> +	bindings map[string]*mqtt.Trie
我觉得不应该是通过配置文件体现，没必要对外暴露，调整的话，可以通过 common 中定义常量方式。

2019-12-23 15:16 UTC, ludanfeng requested changes

2019-12-23 15:16 UTC, ludanfeng commented on common/topic.go
> +	var maxTopicLevels = maxTopicLevels
移除。系统主体移除第一段后，剩下的跟普通主体一样检查就行，也就是剩下的主题也允许9层把

2019-12-23 15:16 UTC, ludanfeng commented on exchange.go
> +	shadow string `default:"$baidu"`
怎么没看到动config.go
type config struct {
	Addresses   []string          `yaml:"addresses" json:"addresses"`
	Certificate utils.Certificate `yaml:"certificate" json:"certificate"`
	Principals  []auth.Principal  `yaml:"principals" json:"principals" validate:"principals"`
	Session     session.Config    `yaml:"session" json:"session"`
	Link        link.ServerConfig `yaml:"link" json:"link"`
         SysTopics []string `yaml:"sysTopics" json:"sysTopics" default:"[\"$link\"]"`
}

移除systemTopic struct

2019-12-23 15:16 UTC, ludanfeng commented on exchange.go
> +	if bind, ok := b.bindings[parts[0]]; ok && (parts[0] == b.systemTopics.shadow || parts[0] == b.systemTopics.link) {
ok&&后面的条件在搞啥啊？

2019-12-23 15:16 UTC, ludanfeng commented on exchange.go
> +}
移除这些特殊的方法

2019-12-23 15:16 UTC, ludanfeng commented on exchange.go
> +	b.UnbindCommonAll(queue)
遍历bindings逐个移除，好好抽象，要求新增一个系统系统主体，不需要改任何代码。

2019-12-23 15:16 UTC, ludanfeng commented on exchange.go
> +	length := 1
length初始化在这里有啥用？

2019-12-23 15:16 UTC, ludanfeng commented on exchange.go
> +	length = len(sss)
length := len(sss)

2019-12-23 15:16 UTC, ludanfeng commented on exchange.go
> +		sss = append(sss, qq...)
不应该是sss = bind.Match(msg.Context.Topic) 吗？

2019-12-23 15:28 UTC, kuailehaibin commented on exchange.go
> +		sss = append(sss, qq...)
$ 开头的主题（认为 $baidu, $link 开头属于系统主题，其他不属于）不应该匹配通配符

2019-12-23 15:29 UTC, kuailehaibin commented on exchange.go
> +	b.UnbindCommonAll(queue)
好的，我调整一下

2019-12-23 15:29 UTC, kuailehaibin commented on exchange.go
> +}
好的

2019-12-23 15:31 UTC, kuailehaibin commented on common/topic.go
> +	var maxTopicLevels = maxTopicLevels
行，这点提测时候跟 QA 反馈一下。

2019-12-23 15:34 UTC, kuailehaibin commented on exchange.go
> +	shadow string `default:"$baidu"`
好的，我调整一下

2019-12-23 15:35 UTC, kuailehaibin commented on exchange.go
> +	length = len(sss)
上面的初始化多余了，忘了删掉

2019-12-24 09:00 UTC, ludanfeng requested changes

2019-12-24 09:00 UTC, ludanfeng commented on exchange.go
> +	sss := make([]interface{}, 0)
var sss []interface{}

2019-12-24 09:00 UTC, ludanfeng commented on session/client_mock_test.go
>  func (b *mockExchange) Bind(topic string, queue common.Queue) {
考虑将exchange.go放进独立的目录，解除循环依赖的问题吧，这样就不用mock exchange了

2019-12-24 09:00 UTC, ludanfeng commented on session/client_mqtt_test.go
> +	fmt.Println("\n--> 4. clear retain message of topic 'test' --> client4 subscribe topic 'test' --> client4 Will not receive message of topic 'test'<--")
增加新的测试case，覆盖如下场景：
1. 使用#订阅普通主题，不会收到系统主题消息
2. 使用$link/#订阅系统主体，不会收到普通主题消息，也不会收到其他系统主题消息
3. 订阅和发布未配置的系统主体，需要报错。也就是主体检查需要能检测出未配置的主题并报错

2019-12-24 09:02 UTC, kuailehaibin commented on exchange.go
> +	sss := make([]interface{}, 0)
好的

2019-12-24 09:03 UTC, kuailehaibin commented on session/client_mock_test.go
>  func (b *mockExchange) Bind(topic string, queue common.Queue) {
好，我调整一下

2019-12-24 09:03 UTC, kuailehaibin commented on session/client_mqtt_test.go
> +	fmt.Println("\n--> 4. clear retain message of topic 'test' --> client4 subscribe topic 'test' --> client4 Will not receive message of topic 'test'<--")
好的

2019-12-24 14:37 UTC, ludanfeng requested changes

2019-12-24 14:37 UTC, ludanfeng commented on common/topic.go
> +func CheckTopic(topic string, sysTopics []string, wildcard bool) bool {
不要每次都传，把CheckTopic变成TopicChecker对象，给session manager初始化一个应该就好了
sysTopics使用map[string]struct{}类型

2019-12-24 14:37 UTC, ludanfeng commented on common/topic.go
> +		if _, found := find(segments[0], sysTopics); !found {
使用白名单检查后，后面的"+"和"#"的检查就没必要了。

2019-12-24 14:37 UTC, ludanfeng commented on common/topic.go
> +func find(val string, slice []string) (int, bool) {
移除

2019-12-24 14:37 UTC, ludanfeng commented on session/client_mock_test.go
> +	for _, bind := range b.manager.exchange.Bindings {
不要直接暴露Bindings，暴露方法

2019-12-24 14:50 UTC, kuailehaibin commented on common/topic.go
> +func CheckTopic(topic string, sysTopics []string, wildcard bool) bool {
好的，我调整一下

2019-12-24 14:50 UTC, kuailehaibin commented on common/topic.go
> +func find(val string, slice []string) (int, bool) {
好的

2019-12-24 14:51 UTC, kuailehaibin commented on session/client_mock_test.go
> +	for _, bind := range b.manager.exchange.Bindings {
嗯，调整一下

2019-12-24 14:51 UTC, kuailehaibin commented on common/topic.go
> +		if _, found := find(segments[0], sysTopics); !found {
嗯嗯，这里的确没必要了

2019-12-25 01:28 UTC, ludanfeng requested changes

2019-12-25 01:28 UTC, ludanfeng commented on common/topic.go
> +	SysTopics map[string]struct{}
不要轻易暴露内部字段，TopicChecker一创建就不允许改变，防止勿用，保证跨协程安全

2019-12-25 02:59 UTC, kuailehaibin commented on common/topic.go
> +	SysTopics map[string]struct{}
好的，我再调整一下

2019-12-25 04:55 UTC, ludanfeng approved these changes

2019-12-25 04:55 UTC, ludanfeng commented on common/topic_test.go
>  	tc := &TopicChecker{
用New

2019-12-25 04:55 UTC, merged