support SSL, Websocket, WSS connection method
baetyl/baetyl-broker pull request #17
Opened 2020-01-07 08:52 UTC by kuailehaibin

support SSL, Websocket, WSS connection method

2020-01-09 07:23 UTC, ludanfeng requested changes

2020-01-09 07:23 UTC, ludanfeng commented on session/client_mqtt_i.go
> +			// if IsBidirectionalAuthentication, will use certificate authentication
注释修改一下

2020-01-09 07:23 UTC, ludanfeng commented on session/client_mqtt_i.go
> +		} else if cn, ok := mqtt.GetTLSCommonName(c.connection); ok {
} else  {
if cn, ok := mqtt.GetTLSCommonName(c.connection); ok {}
else{}
}

2020-01-09 08:04 UTC, kuailehaibin commented on session/client_mqtt_i.go
> +		} else if cn, ok := mqtt.GetTLSCommonName(c.connection); ok {
嗯，调整一下

2020-01-09 08:04 UTC, kuailehaibin commented on session/client_mqtt_i.go
> +			// if IsBidirectionalAuthentication, will use certificate authentication
好的

2020-01-09 08:04 UTC, kuailehaibin commented on session/client_mqtt_i.go
> +			// if IsBidirectionalAuthentication, will use certificate authentication
好的

2020-01-14 02:31 UTC, ludanfeng requested changes

2020-01-14 02:31 UTC, ludanfeng commented on broker_test.go
> +func TestSessionMqttConnectTCP(t *testing.T) {
TestBrokerMqttConnectTCP

2020-01-14 02:31 UTC, ludanfeng commented on broker_test.go
> +	dailer := mqtt.NewDialer(nil, time.Duration(0))
mqtt.NewClient

2020-01-14 02:31 UTC, ludanfeng commented on example/etc/baetyl/service.yml
> +  ca: example/testcert/ca.pem
example/var/lib/baetyl/testcert/ca.pem

2020-01-14 02:31 UTC, ludanfeng commented on session/client_mqtt_i.go
> +				return ErrSessionPasswordNotSet
定义新的err，ErrSessionCommonNameNotFound

2020-01-14 02:31 UTC, ludanfeng commented on session/client_mqtt_i.go
> +					return ErrSessionUsernameNotPermitted
定义新的err，ErrSessionCommonNameNotPermitted

2020-01-14 02:44 UTC, kuailehaibin commented on session/client_mqtt_i.go
> +				return ErrSessionPasswordNotSet
好的

2020-01-14 02:45 UTC, kuailehaibin commented on session/client_mqtt_i.go
> +					return ErrSessionUsernameNotPermitted
好的，调整一下

2020-01-14 02:45 UTC, kuailehaibin commented on example/etc/baetyl/service.yml
> +  ca: example/testcert/ca.pem
OK，调整一下

2020-01-14 02:45 UTC, kuailehaibin commented on broker_test.go
> +func TestSessionMqttConnectTCP(t *testing.T) {
嗯嗯，调整一下

2020-01-14 02:46 UTC, kuailehaibin commented on broker_test.go
> +	dailer := mqtt.NewDialer(nil, time.Duration(0))
我先测试、调整一下，之前是想着直接用这个，但是需要引入 Observer

2020-01-15 03:16 UTC, chensheng0 commented on go.mod
> +	github.com/baetyl/baetyl-go v0.1.3
broker 现在已经是 0.1.4 了，baetyl-go 0.1.4中更新了日志组件

2020-01-15 05:15 UTC, ludanfeng requested changes

2020-01-15 05:15 UTC, ludanfeng commented on session/manager.go
> +	ErrSessionCommonNameNotFound           = errors.New("commonName not found")
tls common name not found

2020-01-15 05:15 UTC, ludanfeng commented on session/manager.go
> +	ErrSessionCommonNameNotPermitted       = errors.New("commonName not permitted")
tls common name not permitted

2020-01-15 07:05 UTC, kuailehaibin commented on session/manager.go
> +	ErrSessionCommonNameNotFound           = errors.New("commonName not found")
嗯嗯，好的

2020-01-15 07:05 UTC, kuailehaibin commented on session/manager.go
> +	ErrSessionCommonNameNotPermitted       = errors.New("commonName not permitted")
嗯嗯

2020-01-15 07:25 UTC, ludanfeng requested changes

2020-01-15 07:25 UTC, ludanfeng commented on session/manager.go
> +	ErrSessionCertificateCommonNameNotFound     = errors.New("commonName not found")
"certificate common name is not found"

2020-01-15 07:59 UTC, ludanfeng approved these changes

2020-01-15 07:59 UTC, merged