Re-check subscriptions, if subscription not permit, log error and skip
baetyl/baetyl-broker pull request #23
Opened 2020-02-04 06:45 UTC by kuailehaibin

Re-check subscriptions, if subscription not permit, log error and skip

2020-02-04 07:58 UTC, ludanfeng requested changes

2020-02-04 07:58 UTC, ludanfeng commented on session/manager.go
> +	if subscriptions := s.Subscriptions; subscriptions != nil {
只有重新加载配置才需要重新检查持久化的session，所以是不是只需要在NewManager里检查加载的session就可以？
另外没有权限的主题是不是得从持久化的session info中移除？

2020-02-04 09:10 UTC, kuailehaibin commented on session/manager.go
> +	if subscriptions := s.Subscriptions; subscriptions != nil {
嗯，我看看调整一下，没权限主题的检查还是得放在 initSession 中

2020-02-04 15:13 UTC, ludanfeng requested changes

2020-02-04 15:13 UTC, ludanfeng commented on session/manager.go
> +				manager.exchange.Unbind(topic, s)
这行多余的吧

2020-02-04 15:13 UTC, ludanfeng commented on session/manager.go
> +			} else {
这几个if else没有关系，写成：
if exception A {
continue
}
if exception B {
continue
}
// to do normal work here

2020-02-04 15:13 UTC, ludanfeng commented on session/manager.go
> +				if !cli.authorize(Subscribe, topic) {
client interface 抽象一个authorize函数出来

2020-02-04 15:16 UTC, kuailehaibin commented on session/manager.go
> +				manager.exchange.Unbind(topic, s)
是，不用，Info 中移除就好了

2020-02-04 15:16 UTC, kuailehaibin commented on session/manager.go
> +			} else {
OK

2020-02-04 15:16 UTC, kuailehaibin commented on session/manager.go
> +				if !cli.authorize(Subscribe, topic) {
好的

2020-02-04 16:01 UTC, ludanfeng requested changes

2020-02-04 16:01 UTC, ludanfeng commented on session/manager.go
> +				delete(si.Subscriptions, topic)
continue别忘了
另外错误级别改成warn吧
加单测吧

2020-02-04 16:01 UTC, ludanfeng commented on session/manager.go
> +				m.log.Error(ErrSessionMessageTopicNotPermitted.Error(), log.Any("topic", topic))
改成warn

2020-02-04 16:01 UTC, ludanfeng commented on session/manager.go
> +	if subs := s.Subscriptions; subs != nil { // subs is not nil, represents s is the restored session
参考
https://www.jianshu.com/p/d276aa7300d1

单测覆盖一下吧

2020-02-04 16:03 UTC, ludanfeng requested changes

2020-02-04 16:03 UTC, ludanfeng commented on session/manager.go
> +				delete(s.Subscriptions, topic)
这里要：manager.exchange.Unbind(topic, s)了吧

2020-02-04 16:04 UTC, kuailehaibin commented on session/manager.go
> +	if subs := s.Subscriptions; subs != nil { // subs is not nil, represents s is the restored session
嗯，明天补一下

2020-02-04 16:08 UTC, kuailehaibin commented on session/manager.go
> +				delete(si.Subscriptions, topic)
嗯嗯，好的

2020-02-04 16:08 UTC, kuailehaibin commented on session/manager.go
> +				m.log.Error(ErrSessionMessageTopicNotPermitted.Error(), log.Any("topic", topic))
OK

2020-02-04 16:16 UTC, kuailehaibin commented on session/manager.go
> +				delete(s.Subscriptions, topic)
是的，需要，NewManager 之后路由已经绑定了，脑子抽了。。。

2020-02-05 12:11 UTC, ludanfeng requested changes

2020-02-05 12:11 UTC, ludanfeng commented on session/manager.go
> +				continue
这里不delete(si.Subscriptions, topic)吗？

2020-02-05 12:11 UTC, ludanfeng commented on session/client_mqtt_test.go
> +func TestSessionMqttCleanSessionWithValidAndPermittedTopic(t *testing.T) {
这个测试就是测CleanSession的逻辑的，跟订阅是否合法没关系，不要改名字。
另外你下面加的两个测试，TestSessionMqttSubscribe都覆盖率了，你要增加的测试得覆盖你pr的changes啊。
需要覆盖两个点：1、持久化的session，在**session.sysTopics配置变化**后，重新启动broker触发订阅删除，比如：之前配置允许系统主题$baidu，后面配置把系统主题$baidu移除了；2.、持久化的session，在**principals配置变化**后，重新启动broker，client重连后触发订阅删除。比如：之前配置允许client订阅主题test，后面配置把主题test移除了；

2020-02-05 12:24 UTC, kuailehaibin commented on session/client_mqtt_test.go
> +func TestSessionMqttCleanSessionWithValidAndPermittedTopic(t *testing.T) {
嗯，想错了，我再改一下

2020-02-06 07:26 UTC, ludanfeng requested changes

2020-02-06 07:26 UTC, ludanfeng commented on session/client_mqtt_test.go
> +	b.close()
b.close() 会把持久化的文件移除，还是没覆盖到，你自己是怎么验证的啊？不看一下有没有打印warn日志吗？

2020-02-06 07:35 UTC, kuailehaibin commented on session/client_mqtt_test.go
> +	b.close()
再补一下日志过程

2020-02-07 05:59 UTC, kuailehaibin commented on session/manager.go
> +				continue
漏了，忘加了，补一下

2020-02-07 06:20 UTC, ludanfeng approved these changes

2020-02-07 06:21 UTC, ludanfeng approved these changes

2020-02-07 06:23 UTC, merged