baetyl-312: code refractor
baetyl/baetyl-broker pull request #46
Opened 2020-07-06 11:24 UTC by chensheng0

2020-07-07 02:28 UTC, ludanfeng requested changes

2020-07-07 02:28 UTC, ludanfeng commented on session/mqtt.go
> +	if len(p.Subscriptions) == 0 {
协议里规定了不能为空吗？

2020-07-07 02:30 UTC, chensheng0 commented on session/mqtt.go
> +	if len(p.Subscriptions) == 0 {
协议规定，具体见：SUBSCRIBE报文的有效载荷必须包含至少一对主题过滤器 和 QoS等级字段组合。没有有效载荷的SUBSCRIBE报文是违反协议的 [MQTT-3.8.3-3]

2020-07-07 02:31 UTC, chensheng0 commented on session/mqtt.go
> +	if len(p.Subscriptions) == 0 {
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html  搜索 MQTT-3.8.3-3

2020-07-09 10:47 UTC, ludanfeng approved these changes

2020-07-09 10:47 UTC, merged