keep order
baetyl/baetyl-broker pull request #49
Opened 2020-08-04 08:26 UTC by chensheng0

2020-08-05 02:54 UTC, chensheng0 commented on store/boltdb.go
> -}
@ludanfeng 那这个地方在实现的时候只能做全 bucket 扫描了

2020-08-05 06:10 UTC, chensheng0 commented on session/dispatcher.go
> +	if id != uint64(d.offset) {
@ludanfeng 此处不能使用 <, 考虑 65535 后变为1 的case

2020-08-05 06:47 UTC, ludanfeng requested changes

2020-08-05 06:47 UTC, ludanfeng commented on session/dispatcher.go
> +	"github.com/256dpi/gomqtt/packet"
baetyl-go已经把"github.com/256dpi/gomqtt/packet"包里，不要在这里直接引用"github.com/256dpi/gomqtt/packet"

2020-08-05 06:47 UTC, ludanfeng commented on session/manager.go
> +	ErrManagerClosed                             = errors.New("manager has closed")
ErrSessionExceedsLimit
ErrSessionManagerClosed

2020-08-05 06:47 UTC, ludanfeng commented on session/mqtt.go
> +	}
session的init会重新check CleanSession，不需要close再重建

2020-08-05 06:47 UTC, ludanfeng commented on session/session.go
> +	updated time.Time
？

2020-08-05 06:47 UTC, ludanfeng commented on session/session.go
>  func (s *Session) gotoState0() {
state的逻辑都可以移掉了，反正你已经在改session的逻辑了

2020-08-05 06:47 UTC, ludanfeng commented on session/session.go
> +	s.info.WillMessage = nil
移除后还得持久化一下吧?

2020-08-05 08:32 UTC, chensheng0 commented on session/session.go
>  func (s *Session) gotoState0() {
这个pr先不做，下个 pr 做

2020-08-05 13:34 UTC, chensheng0 commented on session/mqtt.go
> +	}
3.1.2.4 Clean Session

2020-08-05 13:38 UTC, chensheng0 commented on session/session.go
> +	s.info.WillMessage = nil
done

2020-08-05 13:38 UTC, chensheng0 commented on session/session.go
> +	updated time.Time
removed

2020-08-05 13:38 UTC, chensheng0 commented on session/manager.go
> +	ErrManagerClosed                             = errors.New("manager has closed")
done

2020-08-05 13:38 UTC, chensheng0 commented on session/dispatcher.go
> +	"github.com/256dpi/gomqtt/packet"
done

2020-08-06 02:29 UTC, ludanfeng requested changes

2020-08-06 02:29 UTC, ludanfeng commented on go.mod
> +	github.com/256dpi/gomqtt v0.14.2
不要依赖gomqtt，gomqtt已经被baetyl-go包了
第二次提了

2020-08-06 02:29 UTC, ludanfeng commented on session/manager.go
> +	delete(m.sessions, s.info.ID)
session要close吗？

2020-08-06 02:29 UTC, ludanfeng commented on session/mqtt.go
> +	}
注释一下

2020-08-06 02:29 UTC, ludanfeng commented on session/session.go
> +	client *ClientMQTT
client *ClientMQTT 建议rename吧，cli *Client

2020-08-06 02:29 UTC, ludanfeng commented on session/session.go
> +	if prev := s.client; prev != nil {
按照协议，session的前一个client不需要关了，如果被踢session必须先关闭创建新的session（此时会关闭session的client）？

2020-08-06 02:29 UTC, ludanfeng commented on session/session.go
> +	case STATE1:
这些state咋都加回来了？

2020-08-06 02:29 UTC, ludanfeng commented on session/mqtt.go
> +	}
如果session已经存在，且已经包含了一个client或者cleansession变化，session都得关闭？避免会话复用

2020-08-08 13:21 UTC, ludanfeng requested changes

2020-08-08 13:21 UTC, ludanfeng commented on go.mod
> +	github.com/baetyl/baetyl-go/v2 v2.0.12
17

2020-08-08 13:21 UTC, ludanfeng commented on session/mqtt.go
> +	}
manager统一回收

2020-08-08 13:21 UTC, ludanfeng commented on session/manager.go
> +	if !exists {
直接return就好了，不用报错，client没收到connect packet之前也会delClient

2020-08-08 13:21 UTC, ludanfeng commented on session/manager.go
>  		m.log.Error(ErrConnectionRefuse.Error())
ErrConnectionRefuse  --> ErrSessionManagerClosed

2020-08-08 13:21 UTC, ludanfeng commented on session/manager.go
> +		return err
return nil

2020-08-08 13:21 UTC, ludanfeng commented on queue/temporary.go
> +	//})
可以不注释掉，只要保证，queue close前从exchange里移除，这样就没人写了，读没影响，只要client能处理nil就行。

2020-08-08 13:21 UTC, ludanfeng commented on session/map.go
> +	// it will cause data race if return data directly
？

2020-08-08 13:21 UTC, ludanfeng commented on session/mqtt.go
> +		c.log.Error("number of clients exceeds the limit", log.Any("max", m.cfg.MaxClients))
m.cfg.MaxClients --> max
或者都直接用m.cfg.MaxClients

2020-08-08 13:21 UTC, ludanfeng commented on session/mqtt.go
>  	msg := c.session.will()
if c.session == nil { 不能移除吧，client没收到connect packet之前也可能die吧？

2020-08-08 13:21 UTC, ludanfeng commented on session/session.go
> +	queue   chan *eventWrapper
qos0 --> qos0msg
qos1 --> qos1msg
cache --> qos1pkt
queue --> qos1ack 
都放一起？

2020-08-10 02:25 UTC, chensheng0 commented on session/manager.go
> +		return err
done

2020-08-10 02:25 UTC, chensheng0 commented on session/map.go
> +	// it will cause data race if return data directly
removed

2020-08-10 02:26 UTC, chensheng0 commented on session/mqtt.go
> +		c.log.Error("number of clients exceeds the limit", log.Any("max", m.cfg.MaxClients))
done

2020-08-10 02:33 UTC, chensheng0 commented on session/session.go
> +	queue   chan *eventWrapper
done

2020-08-10 02:35 UTC, chensheng0 commented on session/mqtt.go
>  	msg := c.session.will()
done

2020-08-10 02:35 UTC, chensheng0 commented on go.mod
> +	github.com/baetyl/baetyl-go/v2 v2.0.12
done

2020-08-10 02:36 UTC, chensheng0 commented on session/mqtt.go
> +	}
done

2020-08-10 02:36 UTC, chensheng0 commented on session/manager.go
> +	if !exists {
done

2020-08-10 02:36 UTC, chensheng0 commented on session/manager.go
>  		m.log.Error(ErrConnectionRefuse.Error())
done

2020-08-10 02:45 UTC, chensheng0 commented on queue/temporary.go
> +	//})
还是注释掉，remove from queue and queue close 不是一组同步方法

2020-08-10 04:05 UTC, ludanfeng requested changes

2020-08-10 04:05 UTC, ludanfeng commented on session/manager.go
> +		exists = false
loaded 和 exists 不一致了

2020-08-10 10:10 UTC, ludanfeng approved these changes

2020-08-10 10:11 UTC, merged