add will and retain of mqtt
baetyl/baetyl-broker pull request #7
Opened 2019-12-11 12:44 UTC by kuailehaibin

add will and retain of mqtt

2019-12-12 02:25 UTC, ludanfeng requested changes

2019-12-12 02:25 UTC, ludanfeng commented on session/backend.go
> +func NewRetainBackend(driver, location string) (*retain.Backend, error) {
参考NewQueueBackend

2019-12-12 02:25 UTC, ludanfeng commented on session/client_mqtt.go
> +func (c *ClientMQTT) die(err error, will bool) {
不需要will参数，就看传入的err，err不为nil发送will消息

2019-12-12 02:25 UTC, ludanfeng commented on session/client_mqtt.go
> +		c.manager.removeWill(c.session.ID)
为什么在这里清理will message？will message作为session的一部分不应该在session里管理吗？

2019-12-12 02:25 UTC, ludanfeng commented on session/client_mqtt_i.go
> +		}
检查完把will放进si，如果cleansession为false，会自动保存

2019-12-12 02:25 UTC, ludanfeng commented on session/client_mqtt_i.go
> +	}
移除

2019-12-12 02:25 UTC, ludanfeng commented on session/client_mqtt_test.go
> +	b.assertSession(t.Name(), "{\"ID\":\"TestSessionConnect\",\"Will\":null,\"CleanSession\":false,\"Subscriptions\":null}")
序列化tag加上,omitempty

2019-12-12 02:25 UTC, ludanfeng commented on session/manager.go
> +		return err
移除

2019-12-12 02:25 UTC, ludanfeng commented on session/manager.go
> +	if !msg.Retain {
判断放外面，每条消息进来都调用一次这个函数影响性能

2019-12-12 02:25 UTC, ludanfeng commented on session/manager.go
> +		m.log.Error("failed to persist retain message", log.String("topic", topic))
原始err都不打印？

2019-12-12 02:25 UTC, ludanfeng commented on session/manager.go
> +func (m *Manager) getRetain() ([]*packet.Message, error) {
不应该只返回匹配的吗？

2019-12-12 02:25 UTC, ludanfeng commented on session/manager_test.go
> +package session
这个文件移除

去client_mqtt_test.go里恢复相关的测试

2019-12-12 02:31 UTC, ludanfeng requested changes

2019-12-12 02:31 UTC, ludanfeng commented on session/client_mqtt.go
> +func (c *ClientMQTT) saveWillMessage(p *packet.Connect) error {
移除

2019-12-12 02:31 UTC, ludanfeng commented on session/client_mqtt.go
> +	msg, err := c.manager.getWill(c.session.ID)
不需要向manager拿，直接判断client的session变量是否为空，如果不为空把will message取出来直接发送

2019-12-12 02:31 UTC, ludanfeng commented on session/client_mqtt.go
> +	t := common.NewTrie()
session里已经有一个trie了， c.manager.getRetain()直接放回过滤后的消息

2019-12-12 02:59 UTC, kuailehaibin commented on session/backend.go
> +func NewRetainBackend(driver, location string) (*retain.Backend, error) {
好的

2019-12-12 02:59 UTC, kuailehaibin commented on session/client_mqtt.go
> +func (c *ClientMQTT) die(err error, will bool) {
好的，我调整一下

2019-12-12 03:01 UTC, kuailehaibin commented on session/client_mqtt.go
> +		c.manager.removeWill(c.session.ID)
调整一下，之前想的是清理 will 把 Info 的 will 置空。

2019-12-12 03:01 UTC, kuailehaibin commented on session/client_mqtt_i.go
> +		}
好的

2019-12-12 03:01 UTC, kuailehaibin commented on session/client_mqtt_i.go
> +	}
好的

2019-12-12 03:01 UTC, kuailehaibin commented on session/manager.go
> +		return err
好的

2019-12-12 03:02 UTC, kuailehaibin commented on session/manager.go
> +	if !msg.Retain {
好的，我调整一下

2019-12-12 03:02 UTC, kuailehaibin commented on session/manager.go
> +		m.log.Error("failed to persist retain message", log.String("topic", topic))
嗯，好的

2019-12-12 03:04 UTC, kuailehaibin commented on session/manager.go
> +func (m *Manager) getRetain() ([]*packet.Message, error) {
这个不一样，retain 字段通常是 Publish 报文带的标识，后来订阅（Subscribe 报文是一串主题）主题需要匹配的是所有的 retain 保留消息，如果匹配到了，会立即将所有匹配的 retain 消息转发。

2019-12-12 03:04 UTC, kuailehaibin commented on session/manager_test.go
> +package session
好的

2019-12-12 03:04 UTC, kuailehaibin commented on session/client_mqtt.go
> +func (c *ClientMQTT) saveWillMessage(p *packet.Connect) error {
好的

2019-12-12 03:05 UTC, kuailehaibin commented on session/client_mqtt.go
> +	msg, err := c.manager.getWill(c.session.ID)
好的

2019-12-12 03:05 UTC, kuailehaibin commented on session/client_mqtt.go
> +	t := common.NewTrie()
好的

2019-12-12 10:26 UTC, ludanfeng requested changes

2019-12-12 10:26 UTC, ludanfeng commented on session/client_mqtt.go
> +		c.session.subs.Add(sub.Topic, sub.QOS)
在做什么？sub得时候会自动add到session里的啊？这里为什么又加一遍？
p *packet.Subscribe 这个参数都是不需要得吧

2019-12-12 10:26 UTC, ludanfeng commented on session/manager.go
> +func (m *Manager) getRetain() ([]*packet.Message, error) {
匹配逻辑应该放在这个函数里啊

2019-12-12 10:26 UTC, ludanfeng commented on session/client_mqtt.go
> +		c.session.subs.Add(sub.Topic, sub.QOS)
c.manager.getRetain() 直接放回匹配得消息，Subscriptions由session管理

2019-12-12 10:59 UTC, kuailehaibin commented on session/client_mqtt.go
> +		c.session.subs.Add(sub.Topic, sub.QOS)
好的，我调整一下

2019-12-12 10:59 UTC, kuailehaibin commented on session/manager.go
> +func (m *Manager) getRetain() ([]*packet.Message, error) {
好的

2019-12-12 14:56 UTC, ludanfeng requested changes

2019-12-12 14:56 UTC, ludanfeng commented on session/client_mqtt_test.go
> +	"github.com/256dpi/gomqtt/packet"
不要载gomqtt.go以为的地方出现这个引用

2019-12-12 14:56 UTC, ludanfeng commented on session/client_mqtt_test.go
> +	pub.sendC2S(&common.Connect{ClientID: "pub", Will: &packet.Message{Topic: "test", QOS: 0, Payload: []byte("just for test"), Retain: false}, Username: "u2", Password: "p2", Version: 3})
把&common.Connect{}变成一个局部变量吧，方便复用

2019-12-12 14:56 UTC, ludanfeng commented on session/client_mqtt_test.go
> +	sub.sendC2S(&common.Puback{ID: 1})
QOS=0为什么要ack？

2019-12-12 14:56 UTC, ludanfeng commented on session/session.go
> +	Will          *packet.Message `json:"will,omitempty"` // will message
packet.Message --> common.Message

2019-12-12 14:56 UTC, ludanfeng commented on session/manager.go
> +	for _, pkt := range pkts {
为什么要遍历两次？

2019-12-12 14:56 UTC, ludanfeng commented on session/manager.go
> +		msgs = append(msgs, msg)
session过滤未订阅的主题逻辑去哪了?

2019-12-12 14:56 UTC, ludanfeng commented on session/client_mqtt_test.go
> +
增加持久化的retain消息的检查

2019-12-12 14:56 UTC, ludanfeng commented on session/client_mqtt_test.go
> +	sub3.assertS2CPacket("<Publish ID=0 Message=<Message Topic=\"test\" QOS=0 Retain=false Payload=[111 102 102 108 105 110 101]> Dup=false>")
为什么还会收到retain的消息？第631行发布了retain=false的消息不应该把retian的消息清理掉了吗？

2019-12-12 14:56 UTC, ludanfeng commented on session/client_mqtt_test.go
> +	pkt.Message.Retain = true
多发送一个主题不为test的retain消息

2019-12-12 15:02 UTC, kuailehaibin commented on session/client_mqtt_test.go
> +	sub3.assertS2CPacket("<Publish ID=0 Message=<Message Topic=\"test\" QOS=0 Retain=false Payload=[111 102 102 108 105 110 101]> Dup=false>")
retain 的消息不会清理啊，发送相同 topic 主题消息如果后面 retain设置为 false，只是不会替换原来的 retain 消息，有新的 client 订阅时候还是会触发

2019-12-12 15:07 UTC, kuailehaibin commented on session/client_mqtt_test.go
> +	"github.com/256dpi/gomqtt/packet"
好，调整一下

2019-12-12 15:07 UTC, kuailehaibin commented on session/client_mqtt_test.go
> +	pub.sendC2S(&common.Connect{ClientID: "pub", Will: &packet.Message{Topic: "test", QOS: 0, Payload: []byte("just for test"), Retain: false}, Username: "u2", Password: "p2", Version: 3})
好的

2019-12-12 15:08 UTC, kuailehaibin commented on session/client_mqtt_test.go
> +	sub.sendC2S(&common.Puback{ID: 1})
我检查一下，应该是漏掉了

2019-12-12 15:09 UTC, kuailehaibin commented on session/manager.go
> +	for _, pkt := range pkts {
傻了。。。。

2019-12-12 15:49 UTC, kuailehaibin commented on session/client_mqtt_test.go
> +
好的

2019-12-12 15:49 UTC, kuailehaibin commented on session/manager.go
> +		msgs = append(msgs, msg)
我检查一下

2019-12-12 15:50 UTC, kuailehaibin commented on session/client_mqtt_test.go
> +	pkt.Message.Retain = true
好的

2019-12-13 08:52 UTC, ludanfeng requested changes

2019-12-13 08:52 UTC, ludanfeng commented on go.mod
> +	github.com/gogf/gf v1.10.0
移除

2019-12-13 08:52 UTC, ludanfeng commented on session/client_mqtt.go
> +	if msg.Context.Flags == 0 {
在common/event.go里扩展一个Message的方法
func (m *Message) Retain() bool {
	return m.Context.Flags & 0x1
}

2019-12-13 08:52 UTC, ludanfeng commented on session/client_mqtt.go
> +		if ss := c.session.subs.Match(msg.Context.Topic); len(ss) != 0 {
最前面先判断c.session是否为nil吧

2019-12-13 08:52 UTC, ludanfeng commented on session/client_mqtt.go
> +			for _, s := range ss {
msg.Context.QOS > 0 再遍历修改

2019-12-13 08:52 UTC, ludanfeng commented on session/client_mqtt.go
> +			e := common.Event{Message: msg}
common.NewEvent(msg, 0, nil)

2019-12-13 08:52 UTC, ludanfeng commented on session/client_mqtt_i.go
> +	err := c.retainMessage(msg)
要不要retain的判断放到c.retainMessage(msg)外面来，不要每次收到消息都调用这个函数，影响性能。说第二遍了。

2019-12-13 08:52 UTC, ludanfeng commented on session/session.go
> +	Will          *common.Message `json:"will,omitempty"` // will message
`json:"Will,omitempty"`

大写，都统一一下

2019-12-13 08:54 UTC, kuailehaibin commented on session/session.go
> +	Will          *common.Message `json:"will,omitempty"` // will message
OK

2019-12-13 08:55 UTC, kuailehaibin commented on session/client_mqtt.go
> +	if msg.Context.Flags == 0 {
好的

2019-12-13 08:55 UTC, kuailehaibin commented on go.mod
> +	github.com/gogf/gf v1.10.0
好的

2019-12-13 11:56 UTC, ludanfeng requested changes

2019-12-13 11:56 UTC, ludanfeng commented on common/event.go
> +	return m.Context.Flags > 0
不是大于零，这个是bit map，代码不是给你贴了吗？怎么还写成这样

2019-12-13 11:56 UTC, ludanfeng commented on common/gomqtt.go
> +	qos := uint32(0)
qos := uint32(1)

2019-12-13 11:56 UTC, ludanfeng commented on common/gomqtt.go
> +		}
if us < qos {
			qos = us
                         break
		}

2019-12-13 11:56 UTC, ludanfeng commented on retain/backend.go
> +// Config queue config
queue --> retain

2019-12-13 11:56 UTC, ludanfeng commented on session/clent_mock_test.go
>  	"github.com/baetyl/baetyl-broker/auth"
帮忙改一下文件名，写错了

2019-12-13 11:56 UTC, ludanfeng commented on session/client_mqtt_test.go
> +	pkt.Message.Retain = false
多发送一个主题不为test的retain消息。说第二遍了
后面都不需要订阅"talks"，测试client订阅test的时候不会收到talks。

2019-12-13 11:56 UTC, ludanfeng commented on session/client_mqtt_test.go
> +	b.manager.removeRetain("test")
为什么要这样remove
测试的是移除retian消息的操作，重发test消息，payload设置为nil啊。你看了单测覆盖情况了吗？manager清理retain消息的代码触发了吗？

2019-12-13 12:12 UTC, kuailehaibin commented on session/client_mqtt_test.go
> +	b.manager.removeRetain("test")
OK

2019-12-13 12:12 UTC, kuailehaibin commented on session/client_mqtt_test.go
> +	pkt.Message.Retain = false
好

2019-12-13 12:12 UTC, kuailehaibin commented on session/clent_mock_test.go
>  	"github.com/baetyl/baetyl-broker/auth"
好

2019-12-13 12:40 UTC, kuailehaibin commented on common/event.go
> +	return m.Context.Flags > 0
m.Context.Flags & 0x1 的结果还是 uint32，不是 bool，不比较怎么出来 bool ？

2019-12-14 07:09 UTC, ludanfeng requested changes

2019-12-14 07:09 UTC, ludanfeng commented on retain/backend.go
> +// Config retain config
举一反三

2019-12-14 11:06 UTC, ludanfeng approved these changes

2019-12-14 11:06 UTC, ludanfeng commented on session/manager.go
> +		ExpireTime:    time.Duration(m.config.ExpireDay) * time.Hour,
一天24小时啊 @chensheng0

2019-12-14 12:03 UTC, merged