bce-iot-11040: add compact in db
baetyl/baetyl-broker pull request #8
Opened 2019-12-12 13:31 UTC by chensheng0

2019-12-13 05:40 UTC, ludanfeng requested changes

2019-12-13 05:40 UTC, ludanfeng commented on database/db.go
> +	Compact(time.Time) error
不确切，就叫DelBefore吧

2019-12-13 05:40 UTC, ludanfeng commented on database/sql.go
> +	query := fmt.Sprintf("delete from t where ts < '%s'", ts)
禁止拼接sql，养成习惯

2019-12-13 05:40 UTC, ludanfeng commented on queue/persistence.go
> +	cleanDuration := time.Hour
可配置化

2019-12-13 05:40 UTC, ludanfeng commented on queue/persistence.go
> +	cleanTimer := time.NewTicker(cleanDuration)
没有defer啊

2019-12-13 05:40 UTC, ludanfeng commented on queue/persistence.go
>  			q.log.Debug("queue deletes message from backend when timeout")
第153行代码帮忙移除，感觉是多余的代码

2019-12-13 08:22 UTC, ludanfeng requested changes

2019-12-13 08:22 UTC, ludanfeng commented on database/sql.go
> +	stmt, err := d.Prepare("select id, value from t where id >= ? order by id limit ?")
select应该不需要stmt

2019-12-13 08:22 UTC, ludanfeng commented on database/sql.go
>  		args = append(args, strconv.FormatUint(id, 10))
ids不用转string吧

2019-12-13 08:22 UTC, ludanfeng commented on database/sql.go
> +	stmt, err := d.Prepare(query)
delete也不用stmt
没有返回值的sql都用d.Exec就行

2019-12-13 08:22 UTC, ludanfeng commented on queue/persistence.go
> +	err := q.backend.DelBefore(time.Now().Add(-7 * 24 * time.Hour))
配置化

2019-12-14 06:15 UTC, ludanfeng requested changes

2019-12-14 06:15 UTC, ludanfeng commented on queue/persistence.go
> +	err := q.backend.DelBefore(time.Now().Add(-q.cfg.ExpireTime))
err := q.backend.DelBefore(time.Now().Sub(q.cfg.ExpireTime))

2019-12-14 06:15 UTC, ludanfeng commented on database/sql_test.go
> +func TestSQLiteCompact(t *testing.T) {
TestSQLiteDelExpiredData

2019-12-14 07:21 UTC, chensheng0 commented on queue/persistence.go
> +	err := q.backend.DelBefore(time.Now().Add(-q.cfg.ExpireTime))
time包中的Add和Sub的用法，Add用于计算某个时间之前和之后的时间点，Sub用于计算两个时间差

2019-12-14 07:27 UTC, ludanfeng approved these changes

2019-12-14 07:30 UTC, ludanfeng approved these changes

2019-12-14 07:33 UTC, merged